filebeat.inputs:
- type: container
  paths:
    - '/var/lib/docker/containers/*/*.log'

output.elasticsearch:
  hosts: 'elasticsearch:9200'
  username: elastic
  password: changeme

setup.kibana:
  host: 'kibana:5601'
